services:
    _defaults:
        autowire: true
        autoconfigure: true
    # Chargement des services
    ICS\MailingBundle\Controller\:
        resource: "../src/Controller"
        tags: ['controller.services_arguments']
    ICS\MailingBundle\Service\:
        resource: "../src/Service"
        tags: ['controller.services_arguments']
    # ICS\MailingBundle\Command\:
    #     resource: "../src/Command"
    #     tags: ['controller.services_arguments']
    # ICS\MailingBundle\Twig\:
    #     resource: "../src/Twig"
    #     tags: ['controller.services_arguments']
    # ICS\MailingBundle\Form\:
    #     resource: "../src/Form"
    #     tags: ['controller.services_arguments']
